log:
  level: debug
  methods: false
database:
  user: postgres
  password: shalin123
  host: localhost
  port: 5432
  dbname: grubgo
  sslmode: disable
web_server:
  host: localhost 
  port: 8081
  timeout: 15
